services:
  app:
    build:
      context: .
      target: production
    restart: always
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - caddy_data:/data
      - caddy_config:/config
networks:
  laravel:
volumes:
  caddy_data:
  caddy_config:
